name: CI
on: [pull_request]
env:
  PERL_TEST_HARNESS_DUMP_TAP: /tmp/test-output
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Perl environment
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: 5.34
    - name: Install dependencies
      run: |
        cpanm --reinstall --notest TAP::Formatter::JUnit Path::Tiny
    - name: Run tests
      run: |
        make test
        
    - name : Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: test-output/**/*.xml
        retention-days: 1        